### ISSUE TITLE
save-live-edit needs more config?

### ISSUE THREAD

**Issue by Reggino** [ChrisWren/grunt-node-inspector#15]
Hi,

Great work, thanks! Your grunt tasks works awesome with grunt-concurrent .

I did however run into an issue with the `save-live-edit`-feature. When trying to edit and save a file locally, the following message appears in the console:

```
Saving of live-edit changes back to source files is disabled by configuration.
Change the option "saveLiveEdit" in config.json to enable this feature.
```

Am i missing some configuration here?

**Comment by roysG** [comment]
where can i find the config file?
