### ISSUE TITLE
Dependencies update

### ISSUE THREAD

**Issue by xeroxoid** [ChrisWren/grunt-node-inspector#22]
Any plans on bumping up the node-inspector dependency to the latest (0.8.3 as of now) version?

It seems that the included package (0.7.0) does not play well with the latest Chrome update (Version 40.0.2214.91 x64) as it cannot evaluate and display nested values...

Thanks!

**Comment by ChrisWren** [comment]
Tried to update and the tests failed :(. If you can update and make them pass I will accept a PR. I no longer actively use this.

**Comment by lebolo** [comment]
I checked out the code and updated via:

    "dependencies": {
        "node-inspector": "~0.8.0"
    }

with no problems in `grunt test`. However, I "cleaned" out the installation by running `npm cache clean`, deleting the `node_modules` directory and running `npm install`.
