### ISSUE TITLE
bump node-inspector version

### ISSUE THREAD

**Issue by thedug** [ChrisWren/grunt-node-inspector#30]
Could you bump the node-inspector version to 0.12.3?

grunt-node-inspector is using a version that won't build on my machine.

**Comment by noahleigh** [comment]
I believe I'm running into the same issue when trying to install the dependencies for [MEAN.JS](https://github.com/meanjs/mean).

**Comment by 4kochi** [comment]
Since iojs 3.0 node-inspector cannot be installed. Can you please bump the version to 0.12.3 See:

https://github.com/node-inspector/node-inspector/issues/716

**Comment by Riobe** [comment]
It looks like pull request https://github.com/ChrisWren/grunt-node-inspector/pull/28 will handle this. My team is also unable to install grunt-node-inspector after having moved to Visual Studio 2015 and having most of the team uninstalling 2013.

If you have both, you can do `npm install grunt-node-inspector --msvs_version=2013` to get it to install for now.

**Comment by mattpker** [comment]
+1

**Comment by alexgervais** [comment]
+1

**Comment by aaronjessen** [comment]
`--msvs_verison=2013` (and I've also tried `--msvs_version=2015`) still does not allow me to install `grunt-node-inspector` when I have Visual Studio 2013 and 2015 installed on the same machine (Win 8.1 x64, Node v4.0.0, npm v2.14.2). Like @noahleigh, I'm using MEAN.JS, and I receive the following error:

`npm WARN optional dep failed, continuing bufferutil@1.1.0
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "S:\\Node\\node.exe" "S:\\Node\\node_modules\\npm\\bin\\npm-cli.js
" "install" "grunt-node-inspector" "--msvs_version=2015" "--save-dev"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fal
lback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.`

Is there a lower version of Node/npm that would allow the installation to work (I'm not tied to any specific version of Node, as far as I know [I'm new at this]...I figured it was best to have the most recent)?

**Comment by mattpker** [comment]
@aaronjessen The version of node is the issue, not the version of vs. Try downgrading to Node 0.12.7, that was the last stable before Node v4.

**Comment by aaronjessen** [comment]
A million thanks, @mattpker. After switching to Node 0.12.7 and using `npm install grunt-node-inspector --msvs_version=2015`, I'm back in business.

**Comment by fiznool** [comment]
This should now be fixed as of v0.3.0.
