### ISSUE TITLE
Port to Node.JS 4.x

### ISSUE THREAD

**Issue by vielmetti** [ChrisWren/grunt-node-inspector#32]
Noted here, this package is currently failing to build under Node.JS 4.x.

The upstream issue to track: https://github.com/nodejs/node/issues/2798

Discovered this while getting MeanJS to 4.x, see https://github.com/meanjs/mean/pull/922

**Comment by nicholascioli** [comment]
Don't know if this helps, but it seems the error is in the ws dependency (version 0.7.2). The newer version (version 0.8.0) uses a more recent version of [nan](https://www.npmjs.com/package/nan) that does compile on Node v4.
