### ISSUE TITLE
What runs?  

### ISSUE THREAD

**Issue by base698** [ChrisWren/grunt-node-inspector#33]
grunt node-inspector #what file does this run?  Does it run npm start?  Can you configure it to run another script?

**Comment by fiznool** [comment]
@base698 this module just deals with starting node-inspector. You also need another task in your Gruntfile to start your app with debugging enabled. This is typically achieved using a module such as [grunt-express-server](https://github.com/ericclemmons/grunt-express-server).

I'll try to post an example Gruntfile soon to show how to configure everything correctly.
