### ISSUE TITLE
outdated 

### ISSUE THREAD

**Issue by patrikx3** [ChrisWren/grunt-node-inspector#40]
node-inspector v1.0.0 is released.

**Comment by segheysens** [comment]
I have run into the error described in `node-inspector` issues [#932](https://github.com/node-inspector/node-inspector/pull/932?_pjax=%23js-repo-pjax-container#issuecomment-292776522) & [#905](https://github.com/node-inspector/node-inspector/issues/905). I'll see if I can find time to submit a PR, but would appreciate anybody making this change!

**Comment by fiznool** [comment]
Closed via #41
